<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- Khóa AI (nếu có): dotnet user-secrets set "Ai:ApiKey" "<khóa DeepSeek>" -->
    <UserSecretsId>aives-webrazor</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <!-- Presentation CHỈ tham chiếu Business -->
    <ProjectReference Include="..\AIVES.Business\AIVES.Business.csproj" />
  </ItemGroup>

</Project>
